import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import Database from 'better-sqlite3';
import { main, TARGET } from '../scripts/recover-l1-covered-schw.mjs';

function fixture() {
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'l1-schw-')), dbPath=path.join(dir,'db'), configPath=path.join(dir,'config.json'), backupDir=path.join(dir,'backup'), db=new Database(dbPath);
  db.exec(`CREATE TABLE managed_positions(id INTEGER PRIMARY KEY,created_at TEXT,updated_at TEXT,deleted_at TEXT,broker_account_id TEXT,paper_live TEXT,tenant_id TEXT,sandbox_id TEXT,position_id TEXT,revision INTEGER,symbol TEXT,side TEXT,strategy TEXT,quantity REAL,entry_remaining_qty REAL,entry_price REAL,entry_order_id TEXT,entry_client_order_id TEXT,exit_order_id TEXT,exit_client_order_id TEXT,exit_filled_qty REAL,exit_fill_watermarks TEXT,entry_order_type TEXT,allocation_dollars REAL,stop_loss_price REAL,stop_loss_percent REAL,stop_loss_order_id TEXT,stop_loss_client_order_id TEXT,trailing_stop INTEGER,trailing_percent REAL,take_profit_price REAL,take_profit_percent REAL,take_profit_order_id TEXT,take_profit_client_order_id TEXT,partial_exit_enabled INTEGER,partial_exit_percent REAL,partial_exit_target_percent REAL,partial_exit_target_price REAL,partial_exit_orders TEXT,partial_exit_client_order_id TEXT,protection_fill_watermarks TEXT,status TEXT,current_price REAL,unrealized_pl REAL,unrealized_plpc REAL,remaining_qty REAL,notes TEXT,tags TEXT,closed_at TEXT);
  CREATE TABLE managed_orders(id INTEGER PRIMARY KEY,created_at TEXT,updated_at TEXT,deleted_at TEXT,broker_account_id TEXT,paper_live TEXT,tenant_id TEXT,sandbox_id TEXT,position_id TEXT,role TEXT,purpose TEXT,client_order_id TEXT,broker_order_id TEXT,symbol TEXT,side TEXT,asset_class TEXT,underlying TEXT,position_intent TEXT,order_type TEXT,time_in_force TEXT,requested_qty REAL,filled_qty REAL,filled_avg_price REAL,fill_watermark REAL,limit_price REAL,stop_price REAL,lifecycle TEXT,submission_attempted INTEGER,revision INTEGER,submitted_at TEXT,filled_at TEXT,canceled_at TEXT);
  CREATE TABLE orders(id INTEGER PRIMARY KEY,order_id TEXT,client_order_id TEXT,symbol TEXT,side TEXT,qty REAL,type TEXT,time_in_force TEXT,purpose TEXT,status TEXT,filled_qty REAL,filled_avg_price REAL,revision INTEGER,broker_account_id TEXT,tenant_id TEXT,sandbox_id TEXT,paper_live TEXT,deleted_at TEXT,filled_at TEXT);
  CREATE TABLE unrelated(v TEXT);`);
  const cols=db.prepare('pragma table_info(managed_positions)').all().map(x=>x.name), p=Object.fromEntries(cols.map(k=>[k,null])); Object.assign(p,{id:2,broker_account_id:TARGET.accountId,paper_live:'paper',tenant_id:TARGET.tenantId,sandbox_id:TARGET.sandboxId,position_id:TARGET.positionId,revision:TARGET.revision,symbol:'SCHW',side:'sell',quantity:3,entry_remaining_qty:0,entry_price:99.563333,entry_order_id:TARGET.entryId,entry_client_order_id:TARGET.entryClient,exit_filled_qty:0,exit_fill_watermarks:'null',stop_loss_order_id:TARGET.protection2Id,stop_loss_client_order_id:TARGET.protection2Client,status:'PROTECTION_BLOCKED',remaining_qty:3,notes:'preserve this'}); db.prepare(`INSERT INTO managed_positions (${cols.join(',')}) VALUES (${cols.map(()=>'?')})`).run(...cols.map(k=>p[k]));
  const ins=db.prepare('INSERT INTO managed_orders (broker_account_id,paper_live,tenant_id,sandbox_id,position_id,role,purpose,client_order_id,broker_order_id,symbol,side,asset_class,underlying,position_intent,order_type,time_in_force,requested_qty,filled_qty,filled_avg_price,fill_watermark,lifecycle,submission_attempted,revision,filled_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
  ins.run(TARGET.accountId,'paper',TARGET.tenantId,TARGET.sandboxId,TARGET.positionId,'entry','entry',TARGET.entryClient,TARGET.entryId,'SCHW','sell','us_equity','SCHW','sell_to_open','market','day',3,3,99.563333,3,'filled',1,1,TARGET.entryAt);
  for(const [id,client] of [[TARGET.protection1Id,TARGET.protection1Client],[TARGET.protection2Id,TARGET.protection2Client]]) ins.run(TARGET.accountId,'paper',TARGET.tenantId,TARGET.sandboxId,TARGET.positionId,'protection','protection',client,id,'SCHW','buy','us_equity','SCHW','buy_to_cover','stop','day',3,0,null,0,'canceled',1,1,null);
  db.prepare('INSERT INTO orders VALUES (46,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(TARGET.coverId,TARGET.coverClient,'SCHW','buy',3,'limit','day','entry','filled',3,98.61,4,TARGET.accountId,TARGET.tenantId,TARGET.sandboxId,'paper',null,null); db.prepare('INSERT INTO unrelated VALUES (?)').run('untouched'); db.close();
  fs.writeFileSync(configPath,JSON.stringify({sandboxes:{[TARGET.sandboxId]:{id:TARGET.sandboxId,accountId:TARGET.tenantId}},accounts:[{id:TARGET.tenantId,brokerAccountId:TARGET.accountId,paper:true,baseUrl:'https://paper-api.alpaca.markets',publicKey:'fixture',secretKey:'fixture'}]})); return {dir,dbPath,configPath,backupDir};
}
const health=()=>({agent:'healthy',sandboxes:[{sandboxId:'sbx_956ff9e4',goPid:null,state:{running:false,paused:true}},{sandboxId:TARGET.sandboxId,goPid:null,state:{running:false,paused:true}}]});
const provider=()=>({account:{id:TARGET.accountId},orders:[
 {id:TARGET.precursorId,client_order_id:'catalyst-schw-short-001',symbol:'SCHW',asset_class:'us_equity',side:'sell',qty:'3',status:'canceled',filled_qty:'0'},
 {id:TARGET.entryId,client_order_id:TARGET.entryClient,symbol:'SCHW',asset_class:'us_equity',side:'sell',qty:'3',status:'filled',filled_qty:'3',filled_avg_price:'99.563333',filled_at:TARGET.entryAt},
 {id:TARGET.protection1Id,client_order_id:TARGET.protection1Client,symbol:'SCHW',asset_class:'us_equity',side:'buy',qty:'3',status:'canceled',filled_qty:'0'},
 {id:TARGET.protection2Id,client_order_id:TARGET.protection2Client,symbol:'SCHW',asset_class:'us_equity',side:'buy',qty:'3',status:'canceled',filled_qty:'0'},
 {id:TARGET.coverId,client_order_id:TARGET.coverClient,symbol:'SCHW',asset_class:'us_equity',side:'buy',qty:'3',type:'limit',time_in_force:'day',status:'filled',filled_qty:'3',filled_avg_price:'98.61',filled_at:TARGET.coverAt}],positions:[],open:[]});
function deps(mutator){const state=provider();mutator?.(state);return {Database,health:async()=>health(),fetchFn:async(url,opt)=>{assert.equal(opt.method,'GET');let body;if(url.endsWith('/v2/account'))body=state.account;else if(url.includes('status=all'))body=state.orders;else if(url.includes('status=open'))body=state.open;else if(url.endsWith('/v2/positions'))body=state.positions;else throw Error('unexpected endpoint');return {ok:true,status:200,text:async()=>JSON.stringify(body)}}};}
const args=(f,apply=false,approval='approved-L1-recovery')=>['--config',f.configPath,'--db',f.dbPath,'--backup-dir',f.backupDir,...(apply?['--apply','--approval-ref',approval]:[])];
test('dry-run is read-only and validates complete bounded history',async()=>{const f=fixture(),before=fs.readFileSync(f.dbPath);assert.equal((await main(args(f),deps())).mode,'dry-run');assert.deepEqual(fs.readFileSync(f.dbPath),before);assert.equal(fs.existsSync(f.backupDir),false)});
test('default authenticated health transport accepts only healthy stopped-parent 503',async()=>{const prior=[process.env.BASIC_AUTH_USER,process.env.BASIC_AUTH_PASS];process.env.BASIC_AUTH_USER='fixture-user';process.env.BASIC_AUTH_PASS='fixture-pass';try{const run=async({status=503,brokerStatus=200,mutate=()=>{}}={})=>{const f=fixture(),before=fs.readFileSync(f.dbPath),pd=provider(),h={agent:'healthy',trading_bot:'unavailable',trading_bot_managed:false,sandboxes:[{sandboxId:TARGET.sandboxId,goPid:null,state:{running:false,paused:true}},{sandboxId:'sbx_956ff9e4',goPid:null,state:{running:false,paused:true}}]};mutate(h);const fetchFn=async(url,opt)=>{assert.equal(opt.method,'GET');if(url==='http://127.0.0.1:3737/api/health')assert.equal(opt.headers.Authorization,`Basic ${Buffer.from('fixture-user:fixture-pass').toString('base64')}`);let body,code=200;if(url==='http://127.0.0.1:3737/api/health'){body=h;code=status}else if(url.endsWith('/v2/account')){body=pd.account;code=brokerStatus;}else if(url.includes('status=all'))body=pd.orders;else if(url.includes('status=open'))body=pd.open;else if(url.endsWith('/v2/positions'))body=pd.positions;else throw Error('unexpected endpoint');return{ok:code>=200&&code<300,status:code,text:async()=>JSON.stringify(body)}};return{f,before,fetchFn,promise:()=>main(args(f),{Database,fetchFn})}};const good=await run();assert.equal((await good.promise()).mode,'dry-run');assert.deepEqual(fs.readFileSync(good.f.dbPath),good.before);for(const scenario of [{status:503,brokerStatus:503},{status:500},{status:401},{status:403},{status:200,mutate:h=>h.agent='unhealthy'},{status:503,mutate:h=>h.agent='unhealthy'},{status:503,mutate:h=>h.sandboxes[0].state.running=true},{status:503,mutate:h=>h.sandboxes[1].state.paused=false},{status:503,mutate:h=>h.sandboxes.pop()},{status:503,mutate:h=>h.sandboxes.push({sandboxId:'unknown',goPid:null,state:{running:false,paused:true}})},{status:503,mutate:h=>h.sandboxes[0].goPid=123},{status:503,mutate:h=>h.sandboxes[1].sandboxId=TARGET.sandboxId}]){const x=await run(scenario);await assert.rejects(x.promise());assert.deepEqual(fs.readFileSync(x.f.dbPath),x.before)}const bad=await run();const badFetchFn=async(url,opt)=>{assert.equal(opt.method,'GET');return{ok:false,status:503,text:async()=>'{'}};await assert.rejects(main(args(bad.f),{Database,fetchFn:badFetchFn}));assert.deepEqual(fs.readFileSync(bad.f.dbPath),bad.before)}finally{if(prior[0]===undefined)delete process.env.BASIC_AUTH_USER;else process.env.BASIC_AUTH_USER=prior[0];if(prior[1]===undefined)delete process.env.BASIC_AUTH_PASS;else process.env.BASIC_AUTH_PASS=prior[1]}});
test('accepts exact native SQLite timestamp for the verified entry instant',async()=>{const f=fixture(),d=new Database(f.dbPath);d.prepare('UPDATE managed_orders SET filled_at=? WHERE broker_order_id=?').run('2026-09-24 13:33:36.948594+00:00',TARGET.entryId);d.close();assert.equal((await main(args(f),deps())).mode,'dry-run')});
test('accepts only the two verified cover timestamp serializations and persists the current observation literally',async()=>{const current='2026-10-06T14:12:01.747707Z';for(const filledAt of [TARGET.coverAt,current]){const f=fixture(),d=deps(s=>{s.orders.at(-1).filled_at=filledAt});const dry=await main(args(f),d);assert.equal(dry.broker.filledAt,filledAt);if(filledAt===current){const r=await main(args(f,true),d);assert.equal(r.status,'CLOSED');const q=new Database(f.dbPath,{readonly:true});try{assert.equal(q.prepare('select filled_at from managed_orders where broker_order_id=?').get(TARGET.coverId).filled_at,current);assert.equal(q.prepare('select closed_at from managed_positions where position_id=?').get(TARGET.positionId).closed_at,current)}finally{q.close()}}}const bad=fixture();await assert.rejects(main(args(bad),deps(s=>{s.orders.at(-1).filled_at='2026-10-06T14:12:01.747708Z'})),/cover identity\/fill evidence mismatch/)});
test('apply adds one cover projection and closes only target; fresh DB readback preserves histories',async()=>{const f=fixture(),r=await main(args(f,true),deps());assert.equal(r.revision,TARGET.revision+1);const d=new Database(f.dbPath,{readonly:true});try{const p=d.prepare('select * from managed_positions where id=2').get(),m=d.prepare('select * from managed_orders order by id').all(),o=d.prepare('select * from orders').get();assert.equal(p.status,'CLOSED');assert.equal(p.remaining_qty,0);assert.equal(p.quantity,3);assert.equal(p.closed_at,TARGET.coverAt);assert.equal(m.length,4);assert.equal(m.at(-1).role,'close');assert.equal(m.at(-1).purpose,'close');assert.equal(o.purpose,'entry');assert.equal(o.revision,4);assert.equal(d.prepare('select v from unrelated').get().v,'untouched')}finally{d.close()}await assert.rejects(main(args(f,true),deps()))});
test('apply requires approval reference',async()=>{const f=fixture();await assert.rejects(main(args(f,true,''),deps()),/approval/)});
for(const [name,sql] of [['revision','UPDATE managed_positions SET revision=7'],['sandbox',"UPDATE managed_positions SET sandbox_id='sbx_other'"],['live',"UPDATE managed_positions SET paper_live='live'"]])test(`refuses altered local ${name}`,async()=>{const f=fixture(),d=new Database(f.dbPath);d.exec(sql);d.close();await assert.rejects(main(args(f),deps()))});
for(const [name,column,value] of [['account','broker_account_id','other'],['tenant','tenant_id','other'],['sandbox','sandbox_id','sbx_other'],['live mode','paper_live','live'],['deleted row','deleted_at','2026-10-07T00:00:00Z']])test(`refuses ordinary cover with wrong ${name}`,async()=>{const f=fixture(),d=new Database(f.dbPath);d.prepare(`UPDATE orders SET ${column}=? WHERE order_id=?`).run(value,TARGET.coverId);d.close();await assert.rejects(main(args(f),deps()))});
test('refuses explicit live endpoint and malformed/timeout provider replies',async()=>{const f=fixture(),c=JSON.parse(fs.readFileSync(f.configPath));c.accounts[0].baseUrl='https://api.alpaca.markets';fs.writeFileSync(f.configPath,JSON.stringify(c));await assert.rejects(main(args(f),deps()),/official paper endpoint/);for(const mode of ['malformed','timeout']){const g=fixture(),d=deps();d.fetchFn=async(url,opt)=>{assert.equal(opt.method,'GET');if(mode==='timeout'){const e=Error('private detail');e.name='AbortError';throw e}return{ok:true,status:200,text:async()=>'not-json'}};await assert.rejects(main(args(g),d))}});
test('rechecks stopped parent immediately before transaction',async()=>{const f=fixture(),d=deps();let calls=0;d.health=async()=>{const h=health();if(++calls===3)h.sandboxes.find(x=>x.sandboxId===TARGET.sandboxId).goPid=22;return h};await assert.rejects(main(args(f,true),d),/absent target backend/);assert.equal(fs.existsSync(f.backupDir),true);const q=new Database(f.dbPath,{readonly:true});assert.equal(q.prepare('select revision from managed_positions').get().revision,TARGET.revision);q.close()});
for(const [name,mut] of [['wrong account',s=>s.account.id='other'],['wrong asset',s=>s.orders.at(-1).asset_class='option'],['wrong protection asset',s=>s.orders[2].asset_class='option'],['wrong protection symbol',s=>s.orders[2].symbol='IBM'],['wrong symbol',s=>s.orders.at(-1).symbol='IBM'],['wrong side',s=>s.orders.at(-1).side='sell'],['partial cover',s=>{s.orders.at(-1).filled_qty='2'}],['wrong time',s=>s.orders.at(-1).filled_at='2026-09-01T00:00:00Z'],['extra fill',s=>s.orders.push({...s.orders.at(-1),id:'unexpected'})],['truncated history',s=>{s.orders=Array.from({length:500},(_,i)=>({...s.orders[i%5],id:`page-${i}`}))}],['nonflat',s=>s.positions=[{symbol:'SCHW',qty:'3'}]],['open order',s=>s.open=[{id:'open'}]]]) test(`refuses ${name}`,async()=>{const f=fixture();await assert.rejects(main(args(f),deps(mut)))});
test('requires both parent loops stopped and paused',async()=>{const f=fixture(),d=deps();d.health=async()=>{const h=health();h.sandboxes[0].state.paused=false;return h};await assert.rejects(main(args(f),d),/stopped sandboxes/)});
test('apply rollback on update failure leaves all original rows',async()=>{const f=fixture(),d=new Database(f.dbPath);d.exec("CREATE TRIGGER deny_update BEFORE UPDATE ON managed_positions BEGIN SELECT RAISE(ABORT,'denied'); END");d.close();await assert.rejects(main(args(f,true),deps()));const q=new Database(f.dbPath,{readonly:true});assert.equal(q.prepare('select revision from managed_positions').get().revision,TARGET.revision);assert.equal(q.prepare('select count(*) n from managed_orders').get().n,3);q.close()});

for(const [name,sql] of [['entry price','UPDATE managed_orders SET filled_avg_price=1 WHERE broker_order_id=?'],['entry fill time',"UPDATE managed_orders SET filled_at='2026-09-25T00:00:00Z' WHERE broker_order_id=?"]])test(`refuses altered local ${name}`,async()=>{const f=fixture(),d=new Database(f.dbPath);d.prepare(sql).run(TARGET.entryId);d.close();await assert.rejects(main(args(f),deps()))});
