import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import Database from 'better-sqlite3';import {main,TARGET} from '../scripts/recover-l2-filled-iwm-exit.mjs';
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'l2-fill-')),dbPath=path.join(dir,'db'),configPath=path.join(dir,'config.json'),backupDir=path.join(dir,'backup'),db=new Database(dbPath);
 db.exec(`CREATE TABLE managed_positions(id INTEGER PRIMARY KEY,created_at TEXT,updated_at TEXT,deleted_at TEXT,broker_account_id TEXT,paper_live TEXT,tenant_id TEXT,sandbox_id TEXT,position_id TEXT,revision INTEGER,symbol TEXT,side TEXT,strategy TEXT,quantity REAL,entry_remaining_qty REAL,entry_price REAL,entry_order_id TEXT,entry_client_order_id TEXT,exit_order_id TEXT,exit_client_order_id TEXT,exit_filled_qty REAL,exit_fill_watermarks TEXT,entry_order_type TEXT,allocation_dollars REAL,stop_loss_price REAL,stop_loss_percent REAL,stop_loss_order_id TEXT,stop_loss_client_order_id TEXT,trailing_stop INTEGER,trailing_percent REAL,take_profit_price REAL,take_profit_percent REAL,take_profit_order_id TEXT,take_profit_client_order_id TEXT,partial_exit_enabled INTEGER,partial_exit_percent REAL,partial_exit_target_percent REAL,partial_exit_target_price REAL,partial_exit_orders TEXT,partial_exit_client_order_id TEXT,protection_fill_watermarks TEXT,status TEXT,current_price REAL,unrealized_pl REAL,unrealized_plpc REAL,remaining_qty REAL,notes TEXT,tags TEXT,closed_at TEXT);
 CREATE TABLE managed_orders(id INTEGER PRIMARY KEY,created_at TEXT,updated_at TEXT,deleted_at TEXT,broker_account_id TEXT,paper_live TEXT,tenant_id TEXT,sandbox_id TEXT,position_id TEXT,role TEXT,purpose TEXT,client_order_id TEXT,broker_order_id TEXT,symbol TEXT,side TEXT,asset_class TEXT,underlying TEXT,position_intent TEXT,order_type TEXT,time_in_force TEXT,requested_qty REAL,filled_qty REAL,filled_avg_price REAL,fill_watermark REAL,limit_price REAL,stop_price REAL,lifecycle TEXT,submission_attempted INTEGER,revision INTEGER,submitted_at TEXT,filled_at TEXT,canceled_at TEXT);
 CREATE TABLE orders(id INTEGER PRIMARY KEY,order_id TEXT,client_order_id TEXT,symbol TEXT,side TEXT,qty REAL,type TEXT,time_in_force TEXT,purpose TEXT,status TEXT,filled_qty REAL,filled_avg_price REAL,revision INTEGER);
 CREATE TRIGGER fail_position BEFORE UPDATE ON managed_positions BEGIN SELECT RAISE(ABORT,'forced'); END;`);
 const cols=db.prepare('pragma table_info(managed_positions)').all().map(x=>x.name);const p=Object.fromEntries(cols.map(k=>[k,null]));Object.assign(p,{id:1,broker_account_id:TARGET.accountId,paper_live:'paper',tenant_id:TARGET.tenantId,sandbox_id:TARGET.sandboxId,position_id:TARGET.positionId,revision:6,symbol:'IWM',side:'buy',quantity:1,entry_remaining_qty:0,entry_order_id:TARGET.entryId,entry_client_order_id:TARGET.entryClient,exit_filled_qty:0,exit_fill_watermarks:'{}',stop_loss_order_id:TARGET.stopId,stop_loss_client_order_id:TARGET.stopClient,status:'PROTECTION_BLOCKED',remaining_qty:1,notes:'preserve this'});db.prepare(`INSERT INTO managed_positions (${cols.join(',')}) VALUES (${cols.map(()=>'?')})`).run(...cols.map(k=>p[k]));
 const ins=db.prepare('INSERT INTO managed_orders (broker_account_id,paper_live,tenant_id,sandbox_id,position_id,role,purpose,client_order_id,broker_order_id,symbol,side,requested_qty,filled_qty,fill_watermark,lifecycle,submission_attempted,revision) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');ins.run(TARGET.accountId,'paper',TARGET.tenantId,TARGET.sandboxId,TARGET.positionId,'entry','entry',TARGET.entryClient,TARGET.entryId,'IWM','buy',1,1,1,'filled',1,28);ins.run(TARGET.accountId,'paper',TARGET.tenantId,TARGET.sandboxId,TARGET.positionId,'protection','protection',TARGET.stopClient,TARGET.stopId,'IWM','sell',1,0,0,'canceled',1,27);
 db.prepare('INSERT INTO orders VALUES (24,?,?,?,?,?,?,?,?,?,?,?,?)').run(TARGET.exitId,TARGET.exitClient,'IWM','sell',1,'limit','day','close','filled',1,TARGET.fillPrice,4);db.close();fs.writeFileSync(configPath,JSON.stringify({sandboxes:{[TARGET.sandboxId]:{id:TARGET.sandboxId,accountId:TARGET.tenantId}},accounts:[{id:TARGET.tenantId,brokerAccountId:TARGET.accountId,paper:true,baseUrl:'https://paper-api.alpaca.markets',publicKey:'fixture',secretKey:'fixture'}]}));return{dir,dbPath,configPath,backupDir};}
const stopped=()=>({sandboxes:[{sandboxId:'sbx_723be98b',goPid:14,state:{running:false}},{sandboxId:TARGET.sandboxId,goPid:null,state:{running:false}}]});
function deps(){return{Database,health:async()=>stopped(),fetchFn:async url=>{let body;if(url.endsWith('/v2/account'))body={id:TARGET.accountId};else if(url.endsWith('/'+TARGET.entryId))body={id:TARGET.entryId,client_order_id:TARGET.entryClient,symbol:'IWM',side:'buy',qty:'1',status:'filled',filled_qty:'1',filled_at:'2026-09-24T15:00:00Z'};else if(url.endsWith('/'+TARGET.stopId))body={id:TARGET.stopId,client_order_id:TARGET.stopClient,symbol:'IWM',side:'sell',qty:'1',status:'canceled',filled_qty:'0'};else if(url.endsWith('/'+TARGET.exitId))body={id:TARGET.exitId,client_order_id:TARGET.exitClient,symbol:'IWM',side:'sell',qty:'1',type:'limit',time_in_force:'day',status:'filled',filled_qty:'1',filled_avg_price:'281.85',filled_at:TARGET.fillAt};else body=[];return{ok:true,status:200,text:async()=>JSON.stringify(body)}}};}
const args=(f,apply=false)=>['--config',f.configPath,'--db',f.dbPath,'--backup-dir',f.backupDir,...(apply?['--apply','--approval-ref','incident-approval-1']:[])];
test('accepts canonical Go nil-map watermark only with zero prior exit evidence',async()=>{const f=fixture();const db=new Database(f.dbPath);db.exec('DROP TRIGGER fail_position');db.prepare('UPDATE managed_positions SET exit_fill_watermarks=?').run('null');db.close();assert.equal((await main(args(f),deps())).mode,'dry-run');assert.equal((await main(args(f,true),deps())).revision,7)});
for(const value of ['[]','{"unbound-exit":1}','bad-json',null])test('refuses unknown or nonempty watermark '+String(value),async()=>{const f=fixture();const db=new Database(f.dbPath);db.exec('DROP TRIGGER fail_position');db.prepare('UPDATE managed_positions SET exit_fill_watermarks=?').run(value);db.close();await assert.rejects(main(args(f,true),deps()),/watermark mismatch/)});
test('dry run uses only GET fixture reads and leaves SQLite and backup path unchanged',async()=>{const f=fixture(),d=deps(),methods=[];const fetchFn=d.fetchFn;d.fetchFn=async(u,o)=>{methods.push(o.method);return fetchFn(u,o)};const before=fs.readFileSync(f.dbPath);assert.equal((await main(args(f),d)).mode,'dry-run');assert.deepEqual(new Set(methods),new Set(['GET']));assert.deepEqual(fs.readFileSync(f.dbPath),before);assert.equal(fs.existsSync(f.backupDir),false)});
test('apply binds filled exit, closes target and preserves ordinary history and notes',async()=>{const f=fixture();let d=deps();d.fetchFn=async(u,o)=>{if(!o||o.method!=='GET')throw Error('not GET');return deps().fetchFn(u,o)};d.health=deps().health; // replace trigger to allow guarded write
 const db=new Database(f.dbPath);db.exec('DROP TRIGGER fail_position');db.close();const result=await main(args(f,true),d);assert.equal(result.revision,7);const q=new Database(f.dbPath,{readonly:true});const p=q.prepare('select * from managed_positions').get(),pr=q.prepare("select * from managed_orders where role='close'").get(),ord=q.prepare('select * from orders').get();assert.equal(p.notes.startsWith('preserve this\n[recovery '),true);assert.equal(p.closed_at,TARGET.fillAt);assert.equal(pr.submission_attempted,0);assert.equal(ord.revision,4);q.close();await assert.rejects(main(args(f,true),deps()));});
test('apply rollback on DB failure leaves rows intact',async()=>{const f=fixture();await assert.rejects(main(args(f,true),deps()));const q=new Database(f.dbPath,{readonly:true});assert.equal(q.prepare('select revision from managed_positions').get().revision,6);assert.equal(q.prepare('select count(*) n from managed_orders').get().n,2);q.close()});
test('refuses unhealthy or transitioning parent state and duplicate bindings, including dry run',async()=>{for(const bad of [null,{sandboxes:[{sandboxId:'sbx_723be98b',state:{running:false}},{sandboxId:TARGET.sandboxId,goPid:14,state:{running:false}}]},{sandboxes:[{sandboxId:'sbx_723be98b',state:{running:true}},{sandboxId:TARGET.sandboxId,goPid:null,state:{running:false}}]}]){const f=fixture(),d=deps();d.health=async()=>bad;await assert.rejects(main(args(f),d));}const f=fixture(),d=deps();let n=0;d.health=async()=>++n===1?stopped():({...stopped(),sandboxes:[{sandboxId:'sbx_723be98b',goPid:14,state:{running:false}},{sandboxId:TARGET.sandboxId,goPid:null,state:{running:false}}]});await assert.rejects(main(args(f,true),d));const q=new Database(f.dbPath);q.prepare("INSERT INTO managed_orders (broker_account_id,paper_live,tenant_id,sandbox_id,position_id,role,purpose,client_order_id,broker_order_id) VALUES (?,?,?,?,?,?,?,?,?)").run(TARGET.accountId,'paper',TARGET.tenantId,TARGET.sandboxId,TARGET.positionId,'exit','close',TARGET.exitClient,TARGET.exitId);q.close();await assert.rejects(main(args(f),deps()));});
test('rejects missing quantities and invalid fill times',async()=>{for(const mutation of [b=>{delete b.qty},b=>{b.filled_at='invalid'},b=>{b.filled_at='2026-09-01T00:00:00Z'}]){const f=fixture(),d=deps(),base=d.fetchFn;d.fetchFn=async(u,o)=>{const r=await base(u,o);if(u.endsWith('/'+TARGET.exitId)){const b=JSON.parse(await r.text());mutation(b);return{...r,text:async()=>JSON.stringify(b)}}return r};await assert.rejects(main(args(f),d));}});
test('rejects open broker orders and nonflat positions',async()=>{for(const endpoint of ['/v2/positions','status=open']){const f=fixture(),d=deps(),base=d.fetchFn;d.fetchFn=async(u,o)=>{if(u.includes(endpoint))return{ok:true,status:200,text:async()=>JSON.stringify([{symbol:'IWM',qty:'1'}])};return base(u,o)};await assert.rejects(main(args(f),d));}});
for(const [name,change] of [['wrong account',o=>o.id='other'],['wrong exit client',o=>o.client_order_id='wrong'],['wrong fill',o=>o.filled_qty='0'],['wrong price',o=>o.filled_avg_price='280'],['wrong side',o=>o.side='buy']])test(`rejects ${name}`,async()=>{const f=fixture(),d=deps(),base=d.fetchFn;d.fetchFn=async(u,opt)=>{const r=await base(u,opt);if(u.endsWith('/'+TARGET.exitId)){const b=JSON.parse(await r.text());change(b);return{...r,text:async()=>JSON.stringify(b)}}return r};await assert.rejects(main(args(f),d));});

test('independent: recovered exit uses canonical managed close role',async()=>{const f=fixture();const q=new Database(f.dbPath);q.exec('DROP TRIGGER fail_position');q.close();await main(args(f,true),deps());const db=new Database(f.dbPath,{readonly:true});try{assert.equal(db.prepare('SELECT role FROM managed_orders WHERE broker_order_id=?').get(TARGET.exitId).role,'close')}finally{db.close()}});
function state(f){const db=new Database(f.dbPath,{readonly:true});try{return {position:db.prepare('SELECT revision,status FROM managed_positions').get(),managed:db.prepare('SELECT COUNT(*) AS n FROM managed_orders').get().n,ordinary:db.prepare('SELECT revision FROM orders').get().revision}}finally{db.close()}}
async function withBasic(fn){const old={u:process.env.BASIC_AUTH_USER,p:process.env.BASIC_AUTH_PASS};process.env.BASIC_AUTH_USER='fixture';process.env.BASIC_AUTH_PASS='fixture';try{return await fn()}finally{for(const [k,v]of [['BASIC_AUTH_USER',old.u],['BASIC_AUTH_PASS',old.p]]){if(v===undefined)delete process.env[k];else process.env[k]=v}}}
test('independent: missing parent authentication refuses before writes',async()=>{const f=fixture(),d=deps(),before=state(f);delete d.health;await withBasic(async()=>{delete process.env.BASIC_AUTH_USER;delete process.env.BASIC_AUTH_PASS;await assert.rejects(main(args(f,true),d),/authentication unavailable/)});assert.deepEqual(state(f),before)});
for(const mode of ['http401','abort','malformed'])test('independent: '+mode+' health refuses without database mutation',async()=>{const f=fixture(),d=deps(),before=state(f);delete d.health;d.fetchFn=async(url,opts)=>{assert.equal(url,'http://127.0.0.1:3737/api/health');assert.equal(opts.method,'GET');assert.equal(opts.redirect,'error');if(mode==='abort'){const e=Error('fixture abort');e.name='AbortError';throw e}return {ok:mode!=='http401',status:mode==='http401'?401:200,text:async()=>mode==='malformed'?'not-json':'{}'}};await withBasic(()=>assert.rejects(main(args(f,true),d),mode==='abort'?/timeout/:/verification failed|malformed/));assert.deepEqual(state(f),before)});
test('independent: database changes during broker read are refused, external change preserved',async()=>{const f=fixture(),d=deps(),base=d.fetchFn;const q=new Database(f.dbPath);q.exec('DROP TRIGGER fail_position');q.close();let changed=false;d.fetchFn=async(u,o)=>{const r=await base(u,o);if(!changed&&u.endsWith('/v2/positions')){changed=true;const db=new Database(f.dbPath);db.prepare('UPDATE managed_positions SET revision=99').run();db.close()}return r};await assert.rejects(main(args(f,true),d),/revision|concurrently/);assert.deepEqual(state(f),{position:{revision:99,status:'PROTECTION_BLOCKED'},managed:2,ordinary:4})});
test('independent: runtime starts after initial stopped snapshot, apply refuses',async()=>{const f=fixture(),d=deps(),base=d.health,before=state(f);let calls=0;d.health=async()=>{const h=await base();if(++calls===2)h.sandboxes.find(x=>x.sandboxId===TARGET.sandboxId).goPid=900;return h};await assert.rejects(main(args(f,true),d),/backend absent|stopped/);assert.deepEqual(state(f),before);assert.equal(fs.existsSync(f.backupDir),false)});

