services:
  - type: web
    name: openprophet
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3737
      - key: AGENT_PORT
        value: 3737
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: ALPACA_ENDPOINT
        value: https://paper-api.alpaca.markets
